services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: mhc_backend
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: mhc_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules